apiVersion: v1
kind: Service
metadata:
  name: {{ include "hello-world.name" . }}
  labels:
    chart: {{ include "hello-world.fullname" . }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  ports:
  - name: http
    port: {{ .Values.service.port }}
    targetPort: http
    protocol: TCP
  type: {{ .Values.service.type }}
  selector:
    app: {{ include "hello-world.name" . }}
