{
 "title": "GO RUNTIME METRICS",
 "description": "Process status and runtime metrics published by Go Prometheus client.",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "dc",
    "label": "DC",
    "query": "label_values(go_memstats_alloc_bytes, dc)"
   },
   {
    "name": "service",
    "label": "Service",
    "query": "label_values(go_goroutines{dc=~\"$dc\"}, service)"
   },
   {
    "name": "host",
    "label": "Host",
    "query": "label_values(go_goroutines{dc=~\"$dc\", service=\"$service\"}, hostname)"
   },
   { "name": "interval", "query": "1m,5m,10m,30m,1h" }
  ]
 },
 "panels": [
  {
   "title": "misc",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "GC duration quantiles",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "go_gc_duration_seconds{dc=~\"$dc\",service=\"$service\",hostname=~\"$host\"}",
       "legendFormat": "{{hostname}}: {{quantile}}"
      }
     ]
    },
    {
     "title": "pointer deferences",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "go_memstats_lookups_total{dc=~\"$dc\", service=~\"$service\", hostname=~\"$host\"}",
       "legendFormat": "Pointer dereferences"
      }
     ]
    }
   ]
  },
  {
   "title": "file descriptors",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "open fds",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 2 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "process_open_fds{dc=~\"$dc\",service=\"$service\",hostname=~\"$host\"}",
       "legendFormat": "{{hostname}}"
      }
     ]
    },
    {
     "title": "open fds deriv",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 2 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "deriv(process_open_fds{dc=~\"$dc\",service=\"$service\",hostname=~\"$host\"}[$interval])",
       "legendFormat": "{{hostname}}"
      }
     ]
    }
   ]
  },
  {
   "title": "goroutine stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Goroutines",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 3 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "go_goroutines{dc=~\"$dc\",service=\"$service\",hostname=~\"$host\"}",
       "legendFormat": "{{hostname}}"
      }
     ]
    },
    {
     "title": "OS Threads",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 3 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "go_threads{dc=~\"$dc\", service=\"$service\", hostname=~\"$host\"}",
       "legendFormat": "{{hostname}}"
      }
     ]
    }
   ]
  },
  {
   "title": "go memstats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "alloc bytes allocated",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 11 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "go_memstats_alloc_bytes{dc=~\"$dc\",service=\"$service\",hostname=~\"$host\"}",
       "legendFormat": "{{hostname}} - bytes allocated"
      }
     ]
    },
    {
     "title": "alloc bytes allocated - derivative",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 11 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "deriv(go_memstats_alloc_bytes{dc=~\"$dc\",service=\"$service\",hostname=~\"$host\"}[$interval])",
       "legendFormat": "{{hostname}} - bytes allocated"
      }
     ]
    },
    {
     "title": "stack in use - bytes",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 18 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "go_memstats_stack_inuse_bytes{dc=~\"$dc\",service=\"$service\",hostname=~\"$host\"}",
       "legendFormat": "{{hostname}} - stack inuse"
      }
     ]
    },
    {
     "title": "stack in use - bytes - derivative",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 18 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "deriv(go_memstats_stack_inuse_bytes{dc=~\"$dc\",service=\"$service\",hostname=~\"$host\"}[$interval])",
       "legendFormat": "{{hostname}} - stack inuse"
      }
     ]
    },
    {
     "title": "heap in use - bytes",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 25 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "go_memstats_heap_inuse_bytes{dc=~\"$dc\",service=\"$service\",hostname=~\"$host\"}",
       "legendFormat": "{{hostname}} - heap inuse"
      }
     ]
    },
    {
     "title": "heap in use - bytes - derivative",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 25 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "deriv(go_memstats_heap_inuse_bytes{dc=~\"$dc\",service=\"$service\",hostname=~\"$host\"}[$interval])",
       "legendFormat": "{{hostname}} - heap inuse"
      }
     ]
    },
    {
     "title": "total alloc bytes allocation rate",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 32 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "rate(go_memstats_alloc_bytes_total{dc=~\"$dc\",service=\"$service\",hostname=~\"$host\"}[30s])",
       "legendFormat": "{{hostname}} - alloc rate"
      }
     ]
    }
   ]
  },
  {
   "title": "process memory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "process resident memory",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "process_resident_memory_bytes{dc=~\"$dc\",service=\"$service\",hostname=~\"$host\"}",
       "legendFormat": "{{hostname}} - resident"
      }
     ]
    },
    {
     "title": "process resident memory derivative",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "rate(process_resident_memory_bytes{dc=~\"$dc\",service=\"$service\",hostname=~\"$host\"}[$interval])",
       "legendFormat": "{{hostname}} - resident"
      }
     ]
    },
    {
     "title": "process virtual memory",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "process_virtual_memory_bytes{dc=~\"$dc\",service=\"$service\",hostname=~\"$host\"}",
       "legendFormat": "{{hostname}} - virtual"
      }
     ]
    },
    {
     "title": "process virtual memory derivative",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "deriv(process_virtual_memory_bytes{dc=~\"$dc\",service=\"$service\",hostname=~\"$host\"}[$interval])",
       "legendFormat": "{{hostname}} - virtual"
      }
     ]
    }
   ]
  }
 ]
}