global:
  scrape_interval: "15s"
  evaluation_interval: "15s"

scrape_configs:
  - job_name: "go-hello-world"
    scheme: "http"
    metrics_path: "/metrics"
    static_configs:
      - targets:
          - go-hello-world:5000
